/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.slangproject;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mwg
 */
public class EditSwing extends javax.swing.JFrame {

    /**
     * Creates new form EditSwing
     */
    public EditSwing() {
        initComponents();
        ImageIcon icon =  new ImageIcon("icon/edit.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inPutField = new javax.swing.JTextField();
        inPutButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Slang");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Dosis", 1, 14)); // NOI18N
        jLabel1.setText("Edit Slang");

        jLabel2.setText("Key");

        inPutButton.setText("Edit");
        inPutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPutButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(inPutField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inPutButton)
                        .addGap(79, 293, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backButton))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inPutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(inPutButton)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new JavaSwing().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void inPutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPutButtonActionPerformed
        // TODO add your handling code here:
        String choose = null;
  
        if(Slang.getMultiMap().get(String.valueOf(this.inPutField.getText())) != null){
            String[] option = {"Xoa value", "Them value", "Chinh sua"};
            choose = (String) JOptionPane.showInputDialog(
                this,
                "Ban co cac tinh nang sau",
                "Tinh nang",
                JOptionPane.OK_OPTION,
                null,
                option,
                option[0]
                );
            if(choose == null){return;}
            switch (choose) {
                case "Xoa value" -> {
                    Object[] optionDelete = Slang.findSlangWord(this.inPutField.getText()).toArray();
                    choose = (String) JOptionPane.showInputDialog(
                            this,
                            "Ban co cac tinh nang sau",
                            "Tinh nang",
                            JOptionPane.OK_OPTION,
                            null,
                            optionDelete,
                            optionDelete[0]
                    );
                    if(choose == null){return;}
                    Slang.removeSlangWordValue(this.inPutField.getText(), choose);
                }
                case "Them value" -> {
                    choose = JOptionPane.showInputDialog(this,"Nhap value");
                    if(choose == null){return;}
                    Slang.addSlangWord(this.inPutField.getText(), choose, 2);
                }
                default -> {
                    Object[] optionDelete = Slang.findSlangWord(this.inPutField.getText()).toArray();
                    choose = (String) JOptionPane.showInputDialog(
                            this,
                            "Chon key muon chinh sua",
                            "Chinh sua definition",
                            JOptionPane.OK_OPTION,
                            null,
                            optionDelete,
                            optionDelete[0]
                    );
                    if(choose == null){return;}
                    Slang.removeSlangWordValue(this.inPutField.getText(), choose);
                    choose = (String) JOptionPane.showInputDialog(this,"Nhap value");
                    if(choose == null){return;}
                    Slang.addSlangWord(this.inPutField.getText(), choose, 2);
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Key khong ton tai","Key khong ton tai", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_inPutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton inPutButton;
    private javax.swing.JTextField inPutField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
